@base=http://127.0.0.1:3000/v1
@token=bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklubmVpIiwiY29kZSI6ImVBYXJxaCIsImlkIjoiNWZlZGRmNThkODc0ZjQwZDFkYTQ4MjZmIiwiaWF0IjoxNjA5NDI0NzI4fQ.qp_nnfDJ2OHx-bacE17LICFhLsmS7cpZNp2A_uFiK38
### register
POST  {{base}}/auth/register
Content-Type:  application/json

{
  "username": "Innei",
  "password": "111",
  "email": "tukon479@gmail.com"
}

### login
POST {{base}}/auth/login
Content-Type: application/json

{
  "username": "Innei",
  "password": "111"
  
}

### delete user
DELETE {{base}}/users/
Authorization: {{token}}

### patch user
PATCH {{base}}/users
Authorization: {{token}}
Content-Type: application/json

{
  "email": "tukon479@gmail.com"
}

### get random one
GET {{base}}/sentences

### get random size
GET {{base}}/sentences?count=10

### create
POST {{base}}/sentences/
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklubmVpIiwiY29kZSI6InBKTHpNdSIsImlkIjoiNWZlYzU5YTMxYzg5MTY5OGE4YjhiNjg3IiwiaWF0IjoxNjA5MzI0OTYzfQ.xOAH70DsD7VQkpZnYpWtxen8h6KnxxbWSH8hKoes7OY

{
  "text": "test",
  "from": "",
  "author": "Innei"
}

### update
PATCH {{base}}/sentences/5fec5cd4bccd8f9c7b53d1ee
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklubmVpIiwiY29kZSI6InBKTHpNdSIsImlkIjoiNWZlYzU5YTMxYzg5MTY5OGE4YjhiNjg3IiwiaWF0IjoxNjA5MzI0OTYzfQ.xOAH70DsD7VQkpZnYpWtxen8h6KnxxbWSH8hKoes7OY

{
  "text": "test",
  "from": "",
  "author": "Innei"
}

### delete one
DELETE  {{base}}/sentences/5fec5cd4bccd8f9c7b53d1ee
Content-Type:  application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklubmVpIiwiY29kZSI6InBKTHpNdSIsImlkIjoiNWZlYzU5YTMxYzg5MTY5OGE4YjhiNjg3IiwiaWF0IjoxNjA5MzI0OTYzfQ.xOAH70DsD7VQkpZnYpWtxen8h6KnxxbWSH8hKoes7OY

### get all which this user created
GET {{base}}/sentences/user
Content-Type:  application/json
Authorization: {{token}}

### like a sentence
GET {{base}}/sentences/like/5fed8c8bace5d7a05c09c434
Authorization: {{token}}

### dislike a sentence
DELETE {{base}}/sentences/5fede5015f04b9124234b6fc
Authorization: {{token}}